plugins:
  eslint:
    enabled: true
    channel: "eslint-5"
  sass-lint:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-64
  bundler-audit:
    enabled: true
  brakeman:
    enabled: true
  fixme:
    enabled: true
  flog:
    enabled: true
  reek:
    enabled: true
