AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
